# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'send_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(601, 251)
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(60, 70, 241, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.sending_status = QtWidgets.QLabel(Dialog)
        self.sending_status.setGeometry(QtCore.QRect(360, 60, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sending_status.setFont(font)
        self.sending_status.setObjectName("sending_status")
        self.code_label = QtWidgets.QLabel(Dialog)
        self.code_label.setGeometry(QtCore.QRect(20, 10, 481, 31))
        self.code_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.code_label.setAutoFillBackground(True)
        self.code_label.setObjectName("code_label")
        self.file_name = QtWidgets.QLabel(Dialog)
        self.file_name.setGeometry(QtCore.QRect(60, 120, 81, 41))
        self.file_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.file_name.setObjectName("file_name")
        self.file = QtWidgets.QLabel(Dialog)
        self.file.setGeometry(QtCore.QRect(150, 120, 311, 41))
        self.file.setObjectName("file")
        self.transfer_type = QtWidgets.QLabel(Dialog)
        self.transfer_type.setGeometry(QtCore.QRect(60, 160, 81, 41))
        self.transfer_type.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.transfer_type.setObjectName("transfer_type")
        self.transfer_type_2 = QtWidgets.QLabel(Dialog)
        self.transfer_type_2.setGeometry(QtCore.QRect(150, 160, 131, 41))
        self.transfer_type_2.setObjectName("transfer_type_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.sending_status.setText(_translate("Dialog", "sending"))
        self.code_label.setText(_translate("Dialog", "TextLabel"))
        self.file_name.setText(_translate("Dialog", "TextLabel"))
        self.file.setText(_translate("Dialog", "TextLabel"))
        self.transfer_type.setText(_translate("Dialog", "TextLabel"))
        self.transfer_type_2.setText(_translate("Dialog", "TextLabel"))
