from PyQt5 import QtCore, QtGui, QtWidgets
from ..TabCompleteQLineEdit import TabCompleteQLineEdit
from .window_retranslateUi import w_retranslateUI
from ...service.common import get_platform
from src.service import picture_rc
class main_dialog_render:
    def __init__(self, main_dialog ,MainWindow):
        self._main_dialog = main_dialog
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(524, 515)
        self._main_dialog.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._main_dialog.centralwidget.sizePolicy().hasHeightForWidth())
        self._main_dialog.centralwidget.setSizePolicy(sizePolicy)
        self._main_dialog.centralwidget.setObjectName("centralwidget")
        self._main_dialog.gridLayout_2 = QtWidgets.QGridLayout(self._main_dialog.centralwidget)
        self._main_dialog.gridLayout_2.setObjectName("gridLayout_2")
        self._main_dialog.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self._main_dialog.verticalLayout_3.setObjectName("verticalLayout_3")
        self._main_dialog.tabWidget = QtWidgets.QTabWidget(self._main_dialog.centralwidget)
        self._main_dialog.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self._main_dialog.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self._main_dialog.tabWidget.setIconSize(QtCore.QSize(32, 32))
        self._main_dialog.tabWidget.setObjectName("tabWidget")
        self._main_dialog.tabTransmit = QtWidgets.QWidget()
        self._main_dialog.tabTransmit.setObjectName("tabTransmit")
        self._main_dialog.gridLayout_8 = QtWidgets.QGridLayout(self._main_dialog.tabTransmit)
        self._main_dialog.gridLayout_8.setObjectName("gridLayout_8")
        self._main_dialog.verticalWidget = QtWidgets.QWidget(self._main_dialog.tabTransmit)
        self._main_dialog.verticalWidget.setObjectName("verticalWidget")
        self._main_dialog.verticalLayout = QtWidgets.QVBoxLayout(self._main_dialog.verticalWidget)
        self._main_dialog.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self._main_dialog.verticalLayout.setObjectName("verticalLayout")
        self._main_dialog.frame = QtWidgets.QFrame(self._main_dialog.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self._main_dialog.frame.sizePolicy().hasHeightForWidth())
        self._main_dialog.frame.setSizePolicy(sizePolicy)
        self._main_dialog.frame.setFrameShape(QtWidgets.QFrame.Box)
        self._main_dialog.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self._main_dialog.frame.setObjectName("frame")
        self._main_dialog.gridLayout_13 = QtWidgets.QGridLayout(self._main_dialog.frame)
        self._main_dialog.gridLayout_13.setObjectName("gridLayout_13")
        self._main_dialog.label_3 = QtWidgets.QLabel(self._main_dialog.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self._main_dialog.label_3.sizePolicy().hasHeightForWidth())
        self._main_dialog.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self._main_dialog.label_3.setFont(font)
        self._main_dialog.label_3.setStyleSheet("color: rgb(85, 85, 127);\n"
                                   "font: 75 italic 9pt \"Arial Narrow\";")
        self._main_dialog.label_3.setObjectName("label_3")
        self._main_dialog.gridLayout_13.addWidget(self._main_dialog.label_3, 0, 0, 1, 3)
        self._main_dialog.txtSecretCode = QtWidgets.QLineEdit(self._main_dialog.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self._main_dialog.txtSecretCode.sizePolicy().hasHeightForWidth())
        self._main_dialog.txtSecretCode.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self._main_dialog.txtSecretCode.setFont(font)
        self._main_dialog.txtSecretCode.setText("")
        self._main_dialog.txtSecretCode.setReadOnly(False)
        self._main_dialog.txtSecretCode.setClearButtonEnabled(True)
        self._main_dialog.txtSecretCode.setObjectName("txtSecretCode")
        self._main_dialog.gridLayout_13.addWidget(self._main_dialog.txtSecretCode, 1, 1, 1, 1)
        self._main_dialog.verticalLayout.addWidget(self._main_dialog.frame)
        self._main_dialog.widget_2 = QtWidgets.QWidget(self._main_dialog.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(7)
        sizePolicy.setHeightForWidth(self._main_dialog.widget_2.sizePolicy().hasHeightForWidth())
        self._main_dialog.widget_2.setSizePolicy(sizePolicy)
        self._main_dialog.widget_2.setObjectName("widget_2")
        self._main_dialog.gridLayout_9 = QtWidgets.QGridLayout(self._main_dialog.widget_2)
        self._main_dialog.gridLayout_9.setContentsMargins(0, -1, 0, 0)
        self._main_dialog.gridLayout_9.setObjectName("gridLayout_9")
        self._main_dialog.horizontalLayout = QtWidgets.QHBoxLayout()
        self._main_dialog.horizontalLayout.setObjectName("horizontalLayout")
        self._main_dialog.frame_3 = QtWidgets.QFrame(self._main_dialog.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._main_dialog.frame_3.sizePolicy().hasHeightForWidth())
        self._main_dialog.frame_3.setSizePolicy(sizePolicy)
        self._main_dialog.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self._main_dialog.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self._main_dialog.frame_3.setObjectName("frame_3")
        self._main_dialog.gridLayout_12 = QtWidgets.QGridLayout(self._main_dialog.frame_3)
        self._main_dialog.gridLayout_12.setContentsMargins(6, -1, -1, -1)
        self._main_dialog.gridLayout_12.setObjectName("gridLayout_12")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self._main_dialog.gridLayout_12.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self._main_dialog.gridLayout_12.addItem(spacerItem1, 17, 1, 1, 3)
        self._main_dialog.progressSendFile = QtWidgets.QProgressBar(self._main_dialog.frame_3)
        self._main_dialog.progressSendFile.setProperty("value", 0)
        self._main_dialog.progressSendFile.setObjectName("progressSendFile")
        self._main_dialog.gridLayout_12.addWidget(self._main_dialog.progressSendFile, 16, 0, 1, 4)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self._main_dialog.gridLayout_12.addItem(spacerItem2, 9, 1, 1, 3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self._main_dialog.gridLayout_12.addItem(spacerItem3, 12, 0, 1, 1)
        self._main_dialog.label_9 = QtWidgets.QLabel(self._main_dialog.frame_3)
        self._main_dialog.label_9.setObjectName("label_9")
        self._main_dialog.gridLayout_12.addWidget(self._main_dialog.label_9, 15, 0, 1, 1)
        self._main_dialog.btnSendFile = QtWidgets.QPushButton(self._main_dialog.frame_3)
        self._main_dialog.btnSendFile.setObjectName("btnSendFile")
        self._main_dialog.gridLayout_12.addWidget(self._main_dialog.btnSendFile, 17, 0, 1, 1)
        self._main_dialog.widget_6 = QtWidgets.QWidget(self._main_dialog.frame_3)
        self._main_dialog.widget_6.setObjectName("widget_6")
        self._main_dialog.horizontalLayout_5 = QtWidgets.QHBoxLayout(self._main_dialog.widget_6)
        self._main_dialog.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self._main_dialog.gridLayout_12.addWidget(self._main_dialog.widget_6, 18, 0, 1, 4)
        self._main_dialog.btnBrowseFile = QtWidgets.QPushButton(self._main_dialog.frame_3)
        self._main_dialog.btnBrowseFile.setObjectName("btnBrowseFile")
        self._main_dialog.gridLayout_12.addWidget(self._main_dialog.btnBrowseFile, 9, 0, 1, 1)
        self._main_dialog.txtFileName = QtWidgets.QLineEdit(self._main_dialog.frame_3)
        self._main_dialog.txtFileName.setObjectName("txtFileName")
        self._main_dialog.gridLayout_12.addWidget(self._main_dialog.txtFileName, 7, 0, 2, 4)
        self._main_dialog.label_4 = QtWidgets.QLabel(self._main_dialog.frame_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self._main_dialog.label_4.setFont(font)
        self._main_dialog.label_4.setObjectName("label_4")
        self._main_dialog.gridLayout_12.addWidget(self._main_dialog.label_4, 1, 0, 1, 1)
        self._main_dialog.label_15 = QtWidgets.QLabel(self._main_dialog.frame_3)
        self._main_dialog.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self._main_dialog.label_15.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self._main_dialog.label_15.setObjectName("label_15")
        self._main_dialog.gridLayout_12.addWidget(self._main_dialog.label_15, 13, 0, 1, 1)
        self._main_dialog.label_19 = QtWidgets.QLabel(self._main_dialog.frame_3)
        self._main_dialog.label_19.setText("")
        self._main_dialog.label_19.setObjectName("label_19")
        self._main_dialog.gridLayout_12.addWidget(self._main_dialog.label_19, 14, 0, 1, 1)
        self._main_dialog.label_20 = QtWidgets.QLabel(self._main_dialog.frame_3)
        self._main_dialog.label_20.setObjectName("label_20")
        self._main_dialog.gridLayout_12.addWidget(self._main_dialog.label_20, 13, 1, 1, 1)
        self._main_dialog.label_8 = QtWidgets.QLabel(self._main_dialog.frame_3)
        self._main_dialog.label_8.setObjectName("label_8")
        self._main_dialog.gridLayout_12.addWidget(self._main_dialog.label_8, 3, 0, 1, 1)
        self._main_dialog.horizontalLayout.addWidget(self._main_dialog.frame_3)
        self._main_dialog.gridLayout_9.addLayout(self._main_dialog.horizontalLayout, 0, 0, 1, 1)
        self._main_dialog.verticalLayout.addWidget(self._main_dialog.widget_2)
        self._main_dialog.gridLayout_8.addWidget(self._main_dialog.verticalWidget, 0, 0, 1, 1)
        icon = QtGui.QIcon()
        if get_platform() == 'windows':
            icon.addPixmap(QtGui.QPixmap(":/pic/picture/icon_send.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        else:
            icon.addPixmap(QtGui.QPixmap(""), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self._main_dialog.tabWidget.addTab(self._main_dialog.tabTransmit, icon, "")
        self._main_dialog.tabReceive = QtWidgets.QWidget()
        self._main_dialog.tabReceive.setObjectName("tabReceive")
        self._main_dialog.gridLayout_15 = QtWidgets.QGridLayout(self._main_dialog.tabReceive)
        self._main_dialog.gridLayout_15.setObjectName("gridLayout_15")
        self._main_dialog.widget_4 = QtWidgets.QWidget(self._main_dialog.tabReceive)
        self._main_dialog.widget_4.setObjectName("widget_4")
        self._main_dialog.verticalLayout_2 = QtWidgets.QVBoxLayout(self._main_dialog.widget_4)
        self._main_dialog.verticalLayout_2.setObjectName("verticalLayout_2")
        self._main_dialog.widget_5 = QtWidgets.QWidget(self._main_dialog.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(7)
        sizePolicy.setHeightForWidth(self._main_dialog.widget_5.sizePolicy().hasHeightForWidth())
        self._main_dialog.widget_5.setSizePolicy(sizePolicy)
        self._main_dialog.widget_5.setObjectName("widget_5")
        self._main_dialog.horizontalLayout_3 = QtWidgets.QHBoxLayout(self._main_dialog.widget_5)
        self._main_dialog.horizontalLayout_3.setContentsMargins(0, -1, 0, -1)
        self._main_dialog.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self._main_dialog.frame_5 = QtWidgets.QFrame(self._main_dialog.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._main_dialog.frame_5.sizePolicy().hasHeightForWidth())
        self._main_dialog.frame_5.setSizePolicy(sizePolicy)
        self._main_dialog.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self._main_dialog.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self._main_dialog.frame_5.setObjectName("frame_5")
        self._main_dialog.gridLayout_16 = QtWidgets.QGridLayout(self._main_dialog.frame_5)
        self._main_dialog.gridLayout_16.setContentsMargins(-1, -1, 6, -1)
        self._main_dialog.gridLayout_16.setObjectName("gridLayout_16")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self._main_dialog.gridLayout_16.addItem(spacerItem4, 1, 0, 1, 3)
        self._main_dialog.label_12 = QtWidgets.QLabel(self._main_dialog.frame_5)
        self._main_dialog.label_12.setObjectName("label_12")
        self._main_dialog.gridLayout_16.addWidget(self._main_dialog.label_12, 13, 0, 1, 3)
        self._main_dialog.btnBrowseFolder = QtWidgets.QPushButton(self._main_dialog.frame_5)
        self._main_dialog.btnBrowseFolder.setMinimumSize(QtCore.QSize(0, 0))
        self._main_dialog.btnBrowseFolder.setMaximumSize(QtCore.QSize(100, 16777215))
        self._main_dialog.btnBrowseFolder.setObjectName("btnBrowseFolder")
        self._main_dialog.gridLayout_16.addWidget(self._main_dialog.btnBrowseFolder, 6, 0, 1, 1)
        self._main_dialog.label_13 = QtWidgets.QLabel(self._main_dialog.frame_5)
        self._main_dialog.label_13.setObjectName("label_13")
        self._main_dialog.gridLayout_16.addWidget(self._main_dialog.label_13, 2, 0, 1, 3)
        self._main_dialog.label_17 = QtWidgets.QLabel(self._main_dialog.frame_5)
        self._main_dialog.label_17.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self._main_dialog.label_17.setObjectName("label_17")
        self._main_dialog.gridLayout_16.addWidget(self._main_dialog.label_17, 9, 0, 1, 1)
        self._main_dialog.label_18 = QtWidgets.QLabel(self._main_dialog.frame_5)
        self._main_dialog.label_18.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self._main_dialog.label_18.setObjectName("label_18")
        self._main_dialog.gridLayout_16.addWidget(self._main_dialog.label_18, 11, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self._main_dialog.gridLayout_16.addItem(spacerItem5, 7, 0, 1, 3)
        self._main_dialog.label_11 = QtWidgets.QLabel(self._main_dialog.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self._main_dialog.label_11.setFont(font)
        self._main_dialog.label_11.setObjectName("label_11")
        self._main_dialog.gridLayout_16.addWidget(self._main_dialog.label_11, 0, 0, 1, 3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self._main_dialog.gridLayout_16.addItem(spacerItem6, 12, 0, 1, 3)
        self._main_dialog.txtFolderName = QtWidgets.QLineEdit(self._main_dialog.frame_5)
        self._main_dialog.txtFolderName.setObjectName("txtFolderName")
        self._main_dialog.gridLayout_16.addWidget(self._main_dialog.txtFolderName, 4, 0, 2, 3)
        self._main_dialog.label_14 = QtWidgets.QLabel(self._main_dialog.frame_5)
        self._main_dialog.label_14.setObjectName("label_14")
        self._main_dialog.gridLayout_16.addWidget(self._main_dialog.label_14, 11, 1, 1, 1)
        self._main_dialog.label_16 = QtWidgets.QLabel(self._main_dialog.frame_5)
        self._main_dialog.label_16.setText("")
        self._main_dialog.label_16.setObjectName("label_16")
        self._main_dialog.gridLayout_16.addWidget(self._main_dialog.label_16, 8, 0, 1, 3)
        self._main_dialog.progressRecvFile = QtWidgets.QProgressBar(self._main_dialog.frame_5)
        self._main_dialog.progressRecvFile.setProperty("value", 0)
        self._main_dialog.progressRecvFile.setObjectName("progressRecvFile")
        self._main_dialog.gridLayout_16.addWidget(self._main_dialog.progressRecvFile, 14, 0, 1, 3)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self._main_dialog.gridLayout_16.addItem(spacerItem7, 10, 1, 1, 1)
        self._main_dialog.label_5 = QtWidgets.QLabel(self._main_dialog.frame_5)
        self._main_dialog.label_5.setObjectName("label_5")
        self._main_dialog.gridLayout_16.addWidget(self._main_dialog.label_5, 9, 1, 1, 2)
        self._main_dialog.horizontalLayout_3.addWidget(self._main_dialog.frame_5)
        self._main_dialog.verticalLayout_2.addWidget(self._main_dialog.widget_5)
        self._main_dialog.gridLayout_15.addWidget(self._main_dialog.widget_4, 1, 0, 1, 1)
        self._main_dialog.frame_4 = QtWidgets.QFrame(self._main_dialog.tabReceive)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self._main_dialog.frame_4.sizePolicy().hasHeightForWidth())
        self._main_dialog.frame_4.setSizePolicy(sizePolicy)
        self._main_dialog.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self._main_dialog.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self._main_dialog.frame_4.setObjectName("frame_4")
        self._main_dialog.gridLayout_14 = QtWidgets.QGridLayout(self._main_dialog.frame_4)
        self._main_dialog.gridLayout_14.setContentsMargins(6, -1, -1, -1)
        self._main_dialog.gridLayout_14.setObjectName("gridLayout_14")
        self._main_dialog.btnSetCodeRecv = QtWidgets.QPushButton(self._main_dialog.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._main_dialog.btnSetCodeRecv.sizePolicy().hasHeightForWidth())
        self._main_dialog.btnSetCodeRecv.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pic/picture/img_button_rec.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self._main_dialog.btnSetCodeRecv.setIcon(icon1)
        self._main_dialog.btnSetCodeRecv.setIconSize(QtCore.QSize(32, 32))
        self._main_dialog.btnSetCodeRecv.setObjectName("btnSetCodeRecv")
        self._main_dialog.gridLayout_14.addWidget(self._main_dialog.btnSetCodeRecv, 1, 2, 1, 1)
        self._main_dialog.label_10 = QtWidgets.QLabel(self._main_dialog.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self._main_dialog.label_10.sizePolicy().hasHeightForWidth())
        self._main_dialog.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self._main_dialog.label_10.setFont(font)
        self._main_dialog.label_10.setStyleSheet("font: 75 italic 9pt \"Arial Narrow\";\n"
                                    "color: rgb(85, 85, 127);")
        self._main_dialog.label_10.setObjectName("label_10")
        self._main_dialog.gridLayout_14.addWidget(self._main_dialog.label_10, 0, 0, 1, 1)
        self._main_dialog.txtSecretCodeRecv = TabCompleteQLineEdit(self._main_dialog.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self._main_dialog.txtSecretCodeRecv.sizePolicy().hasHeightForWidth())
        self._main_dialog.txtSecretCodeRecv.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self._main_dialog.txtSecretCodeRecv.setFont(font)
        self._main_dialog.txtSecretCodeRecv.setFocusPolicy(QtCore.Qt.StrongFocus)
        self._main_dialog.txtSecretCodeRecv.setText("")
        self._main_dialog.txtSecretCodeRecv.setReadOnly(False)
        self._main_dialog.txtSecretCodeRecv.setClearButtonEnabled(True)
        self._main_dialog.txtSecretCodeRecv.setObjectName("txtSecretCodeRecv")
        self._main_dialog.gridLayout_14.addWidget(self._main_dialog.txtSecretCodeRecv, 1, 0, 1, 1)
        self._main_dialog.gridLayout_15.addWidget(self._main_dialog.frame_4, 0, 0, 1, 1)
        icon2 = QtGui.QIcon()
        if get_platform() == 'windows':
            icon2.addPixmap(QtGui.QPixmap(":/pic/picture/img_tab_rec.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        else:
            icon2.addPixmap(QtGui.QPixmap(""), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self._main_dialog.tabWidget.addTab(self._main_dialog.tabReceive, icon2, "")
        self._main_dialog.tabSettings = QtWidgets.QWidget()
        self._main_dialog.tabSettings.setObjectName("tabSettings")
        self._main_dialog.gridLayout_3 = QtWidgets.QGridLayout(self._main_dialog.tabSettings)
        self._main_dialog.gridLayout_3.setObjectName("gridLayout_3")
        self._main_dialog.gridLayout_7 = QtWidgets.QGridLayout()
        self._main_dialog.gridLayout_7.setObjectName("gridLayout_7")
        self._main_dialog.widget_1 = QtWidgets.QWidget(self._main_dialog.tabSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._main_dialog.widget_1.sizePolicy().hasHeightForWidth())
        self._main_dialog.widget_1.setSizePolicy(sizePolicy)
        self._main_dialog.widget_1.setObjectName("widget_1")
        self._main_dialog.gridLayout = QtWidgets.QGridLayout(self._main_dialog.widget_1)
        self._main_dialog.gridLayout.setObjectName("gridLayout")
        self._main_dialog.btnSaveSetup = QtWidgets.QPushButton(self._main_dialog.widget_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._main_dialog.btnSaveSetup.sizePolicy().hasHeightForWidth())
        self._main_dialog.btnSaveSetup.setSizePolicy(sizePolicy)
        self._main_dialog.btnSaveSetup.setMinimumSize(QtCore.QSize(250, 0))
        self._main_dialog.btnSaveSetup.setObjectName("btnSaveSetup")
        self._main_dialog.gridLayout.addWidget(self._main_dialog.btnSaveSetup, 0, 0, 1, 1)
        self._main_dialog.gridLayout_7.addWidget(self._main_dialog.widget_1, 1, 0, 1, 1)
        self._main_dialog.widget_7 = QtWidgets.QWidget(self._main_dialog.tabSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._main_dialog.widget_7.sizePolicy().hasHeightForWidth())
        self._main_dialog.widget_7.setSizePolicy(sizePolicy)
        self._main_dialog.widget_7.setObjectName("widget_7")
        self._main_dialog.formLayout = QtWidgets.QFormLayout(self._main_dialog.widget_7)
        self._main_dialog.formLayout.setContentsMargins(100, -1, 100, -1)
        self._main_dialog.formLayout.setHorizontalSpacing(20)
        self._main_dialog.formLayout.setObjectName("formLayout")
        self._main_dialog.label = QtWidgets.QLabel(self._main_dialog.widget_7)
        self._main_dialog.label.setObjectName("label")
        self._main_dialog.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self._main_dialog.label)
        self._main_dialog.txtRelay = QtWidgets.QLineEdit(self._main_dialog.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._main_dialog.txtRelay.sizePolicy().hasHeightForWidth())
        self._main_dialog.txtRelay.setSizePolicy(sizePolicy)
        self._main_dialog.txtRelay.setText("")
        self._main_dialog.txtRelay.setObjectName("txtRelay")
        self._main_dialog.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self._main_dialog.txtRelay)
        self._main_dialog.label_7 = QtWidgets.QLabel(self._main_dialog.widget_7)
        self._main_dialog.label_7.setObjectName("label_7")
        self._main_dialog.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self._main_dialog.label_7)
        self._main_dialog.txtTransit = QtWidgets.QLineEdit(self._main_dialog.widget_7)
        self._main_dialog.txtTransit.setObjectName("txtTransit")
        self._main_dialog.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self._main_dialog.txtTransit)
        self._main_dialog.label_2 = QtWidgets.QLabel(self._main_dialog.widget_7)
        self._main_dialog.label_2.setObjectName("label_2")
        self._main_dialog.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self._main_dialog.label_2)
        self._main_dialog.txtAppID = QtWidgets.QLineEdit(self._main_dialog.widget_7)
        self._main_dialog.txtAppID.setObjectName("txtAppID")
        self._main_dialog.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self._main_dialog.txtAppID)
        self._main_dialog.label_6 = QtWidgets.QLabel(self._main_dialog.widget_7)
        self._main_dialog.label_6.setObjectName("label_6")
        self._main_dialog.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self._main_dialog.label_6)
        self._main_dialog.cmbLanguage = QtWidgets.QComboBox(self._main_dialog.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._main_dialog.cmbLanguage.sizePolicy().hasHeightForWidth())
        self._main_dialog.cmbLanguage.setSizePolicy(sizePolicy)
        self._main_dialog.cmbLanguage.setMinimumSize(QtCore.QSize(150, 0))
        self._main_dialog.cmbLanguage.setObjectName("cmbLanguage")
        self._main_dialog.cmbLanguage.addItem("")
        self._main_dialog.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self._main_dialog.cmbLanguage)
        self._main_dialog.gridLayout_7.addWidget(self._main_dialog.widget_7, 0, 0, 1, 1)
        self._main_dialog.gridLayout_3.addLayout(self._main_dialog.gridLayout_7, 0, 0, 1, 1)
        # icon3 = QtGui.QIcon()
        # icon3.addPixmap(QtGui.QPixmap(":/newPrefix/icons/preferences-system-4.png"), QtGui.QIcon.Normal,
        #                 QtGui.QIcon.Off)
        # self._main_dialog.tabWidget.addTab(self._main_dialog.tabSettings, icon3, "")
        self._main_dialog.tab = QtWidgets.QWidget()
        self._main_dialog.tab.setObjectName("tab")
        self._main_dialog.gridLayout_11 = QtWidgets.QGridLayout(self._main_dialog.tab)
        self._main_dialog.gridLayout_11.setObjectName("gridLayout_11")
        self._main_dialog.txtLog = QtWidgets.QPlainTextEdit(self._main_dialog.tab)
        self._main_dialog.txtLog.setReadOnly(True)
        self._main_dialog.txtLog.setObjectName("txtLog")
        self._main_dialog.gridLayout_11.addWidget(self._main_dialog.txtLog, 0, 0, 1, 1)
        icon4 = QtGui.QIcon()
        if get_platform() == 'windows':
            icon4.addPixmap(QtGui.QPixmap(":/pic/picture/icon_logging"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        else:
            icon4.addPixmap(QtGui.QPixmap(""), QtGui.QIcon.Normal,
                            QtGui.QIcon.Off)
        self._main_dialog.tabWidget.addTab(self._main_dialog.tab, icon4, "")
        self._main_dialog.verticalLayout_3.addWidget(self._main_dialog.tabWidget)
        self._main_dialog.gridLayout_2.addLayout(self._main_dialog.verticalLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self._main_dialog.centralwidget)
        self._main_dialog.menubar = QtWidgets.QMenuBar(MainWindow)
        self._main_dialog.menubar.setGeometry(QtCore.QRect(0, 0, 524, 23))
        self._main_dialog.menubar.setObjectName("menubar")
        self._main_dialog.menuHelp = QtWidgets.QMenu(self._main_dialog.menubar)
        self._main_dialog.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self._main_dialog.menubar)
        self._main_dialog.statusbar = QtWidgets.QStatusBar(MainWindow)
        self._main_dialog.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self._main_dialog.statusbar)
        self._main_dialog.actionWormhole = QtWidgets.QAction(MainWindow)
        self._main_dialog.actionWormhole.setObjectName("actionWormhole")
        self._main_dialog.actionOpenFile = QtWidgets.QAction(MainWindow)
        self._main_dialog.actionOpenFile.setObjectName("actionOpenFile")
        self._main_dialog.actionQuit = QtWidgets.QAction(MainWindow)
        self._main_dialog.actionQuit.setObjectName("actionQuit")
        self._main_dialog.actionViewGraph = QtWidgets.QAction(MainWindow)
        self._main_dialog.actionViewGraph.setObjectName("actionViewGraph")
        self._main_dialog.actionAbout = QtWidgets.QAction(MainWindow)
        self._main_dialog.actionAbout.setObjectName("actionAbout")
        self._main_dialog.menuHelp.addAction(self._main_dialog.actionAbout)
        self._main_dialog.menubar.addAction(self._main_dialog.menuHelp.menuAction())

        w_retranslateUI(self._main_dialog, MainWindow)
        self._main_dialog.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        